{
 "title": "Email Service",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Garbage Collector: Objects Collected (Total) - Email Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(python_gc_objects_collected_total{application=\"Email Service Application\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Garbage Collector: Uncollectable Objects (Total) - Email Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(python_gc_objects_uncollectable_total{application=\"Email Service Application\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process Virtual Memory Usage - Email Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(process_virtual_memory_bytes{application=\"Email Service Application\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process Resident Memory Usage - Email Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(process_resident_memory_bytes{application=\"Email Service Application\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage: Total Time Spent - Email Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{application=\"Email Service Application\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process Start Time - Email Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(process_start_time_seconds{application=\"Email Service Application\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process Total Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(email_processed_count_total{application=\"Email Service Application\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Send Duration Created",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "rate(email_send_duration_created{application=\"Email Service Application\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}