{
 "title": "Topup Service",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Garbage Collector: Objects Collected (Total) - Topup Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(python_gc_objects_collected_total{application=\"Topup Service Application\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Garbage Collector: Uncollectable Objects (Total) - Topup Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(python_gc_objects_uncollectable_total{application=\"Topup Service Application\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process Virtual Memory Usage - Topup Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(process_virtual_memory_bytes{application=\"Topup Service Application\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process Resident Memory Usage - Topup Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(process_resident_memory_bytes{application=\"Topup Service Application\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage: Total Time Spent - Topup Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{application=\"Topup Service Application\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process Start Time - Topup Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(process_start_time_seconds{application=\"Topup Service Application\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Count Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(topup_service_requests_count_total{application=\"Topup Service Application\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Duration Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "rate(topup_service_request_duration_seconds_created{application=\"Topup Service Application\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}