{
 "title": "Transfer Service",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Garbage Collector: Objects Collected (Total) - Transfer Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(python_gc_objects_collected_total{application=\"Transfer Service Application\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Garbage Collector: Uncollectable Objects (Total) - Auth Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(python_gc_objects_uncollectable_total{application=\"Transfer Service Application\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process Virtual Memory Usage - Transfer Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(process_virtual_memory_bytes{application=\"Transfer Service Application\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process Resident Memory Usage - Transfer Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(process_resident_memory_bytes{application=\"Transfer Service Application\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage: Total Time Spent - Transfer Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{application=\"Transfer Service Application\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process Start Time - Transfer Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(process_start_time_seconds{application=\"Transfer Service Application\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}