{
 "title": "User Service",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Garbage Collector: Objects Collected (Total) - User Service",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(python_gc_objects_collected_total{application=\"User Service Application\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Garbage Collector: Uncollectable Objects (Total) - User Service",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(python_gc_objects_uncollectable_total{application=\"User Service Application\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process Resident Memory Usage - User Service",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(process_resident_memory_bytes{application=\"User Service Application\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process Virtual Memory Usage - User Service",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(process_virtual_memory_bytes{application=\"User Service Application\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage: Total Time Spent - User Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{application=\"User Service Application\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process Start Time - User Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "rate(process_start_time_seconds{application=\"User Service Application\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "rate(user_service_request_duration_seconds_created{application=\"User Service Application\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(user_service_request_duration_seconds_bucket{endpoint=\"/\"}[1m])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}